/**
 * docs-notify.js — engine module for the post-publish handoff memo to Docs.
 *
 * Per yesterday's resolved CLI B design decision #2: auto-drop a short
 * structured memo to mailboxes/docs/inbox/ (CC PM) after a successful
 * publish + push, so Docs can pick up Steps 6+ on their next inbox sweep.
 *
 * Per today's Docs feedback memo (signal #3): include the structured JSON
 * exit report content inside the memo body so /update-calendar can read
 * the fields directly — "structured-stdout-as-structured-stdin" is the
 * bridge between script and skill.
 *
 * Per the extend-existing-mechanisms principle: reuse the inbox channel
 * rather than introducing a new log file or surface.
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const REPO_ROOT = path.resolve(__dirname, '..', '..');
const DOCS_INBOX = path.resolve(REPO_ROOT, '..', 'piper-morgan-product', 'mailboxes', 'docs', 'inbox');

/**
 * Drop a publish-handoff memo to docs's inbox. Returns the absolute path of
 * the memo written, or null if the inbox directory doesn't exist (deploys
 * without sibling product-repo checkout).
 *
 * Memo template — short and structured per design decision #2 + today's
 * JSON-in-memo signal.
 */
export function dropPublishHandoffMemo({ title, slug, hashId, url, category, pubDate, websiteCommit, imageAlt, imageCaption }) {
  if (!fs.existsSync(DOCS_INBOX)) {
    return { ok: false, reason: `Docs inbox not found at ${DOCS_INBOX}` };
  }
  const today = new Date().toISOString().slice(0, 10);
  const filename = `memo-web-to-docs-cc-pm-publish-handoff-${slug}-${today}.md`;
  const fullPath = path.join(DOCS_INBOX, filename);

  // Structured fields block — /update-calendar can read these directly
  const structuredJson = JSON.stringify({
    slug,
    hashId,
    blogURL: `https://pipermorgan.ai${url}/`,
    blogPath: url,
    title,
    category,
    pubDate,
    imageAlt: imageAlt || '',
    imageCaption: imageCaption || '',
    websiteCommit,
  }, null, 2);

  const body = `# Memo: Publish handoff — ${title}

**From**: Unicorn Web Designer (web, via publish-cli.js)
**To**: Documentation Management (docs)
**CC**: PM (xian)
**Date**: ${today}
**Re**: Publish landed; Steps 6+ ready for you

---

## What happened

Published just now via \`publish-cli.js\` (engine: \`publish-post.js\`):

- **Title**: ${title}
- **Live URL**: https://pipermorgan.ai${url}/
- **hashId**: \`${hashId}\`
- **Slug**: ${slug}
- **Category**: ${category}
- **pubDate**: ${pubDate}
- **Website commit**: \`${websiteCommit}\`

## Calendar fields written by publish-cli.js

- (none — calendar still authoritatively written by \`/update-calendar\` skill per skill v0.11+)

## What's pending for Docs

Per skill v0.16 procedure:

- **Step 6** (after PM syndicates): \`/update-calendar\` to backfill \`status=published\`, \`blogURL\`, \`blogPath\`, \`canonicalSite=distributed\`, \`mediumURL\`, \`linkedinURL\`, \`altText\`, \`caption\`
- **Step 7**: commit product repo
- **Step 9** (after syndication confirmed): drafts archival — \`drafts/published/\` for the .md, \`drafts/images-archive/\` for the source image

## Structured data (for \`/update-calendar\` consumption)

\`\`\`json
${structuredJson}
\`\`\`

The fields above can be pulled directly into the calendar row at update time. Per Docs's 2026-05-18 feedback memo signal #3: this is the script→skill handoff in structured-stdout-as-structured-stdin form.

---

*Auto-generated by \`publish-cli.js\` engine module \`docs-notify.js\`. If this memo cadence becomes noisy, ping web and we'll evolve the channel.*
`;

  fs.writeFileSync(fullPath, body, 'utf-8');
  return { ok: true, path: fullPath };
}
