name: Deploy Piper Morgan Website to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:
  repository_dispatch:
    types: [blog-posts-updated]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Cache Next.js build
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js site
        run: npm run build
        env:
          NEXT_PUBLIC_GA_MEASUREMENT_ID: ${{ secrets.NEXT_PUBLIC_GA_MEASUREMENT_ID }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: gh-pages
          cname: pipermorgan.ai

      - name: Notify on deployment failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const title = 'Website Deployment Failed';
            const body = `
            ## 🚨 Website Deployment Failed
            
            **Workflow:** Deploy Piper Morgan Website to GitHub Pages  
            **Run:** [#${{ github.run_number }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})  
            **Trigger:** ${{ github.event_name }}  
            **Branch:** ${{ github.ref_name }}  
            **Commit:** [\`${{ github.sha }}\`](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})  
            
            The website deployment to GitHub Pages has failed. This may be due to:
            - Build errors (TypeScript, linting, or compilation issues)
            - Medium RSS feed fetch failures
            - GitHub Pages deployment issues
            - Dependency problems
            
            Please check the [workflow logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details.
            
            **Next Steps:**
            1. Review build logs for specific error details
            2. Check local build with \`npm run build\`
            3. Fix any issues and push changes
            4. Monitor [GitHub Pages deployment](https://github.com/${{ github.repository }}/deployments)
            `;
            
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              body: body,
              labels: ['bug', 'deployment', 'github-pages']
            })
